- action:
  - alias: Kitchen
    data:
      color_temp: 100
    service: light.turn_on
    entity_id: light.kitchen
  alias: Turn on kitchen light when there is motion
  condition: []
  id: '1506385471633'
  trigger:
  - entity_id: binary_sensor.Blue
    platform: state
    to: 'on'
- action:
  - alias: Kitchen
    service: light.turn_off
    entity_id: light.kitchen
  alias: Turn off Kitchen Light
  condition: []
  id: '1506386785372'
  trigger:
  - entity_id: binary_sensor.Blue
    for:
      minutes: 10
    platform: state
    to: 'off'
- action:
  - delay: 00:00:20
  - service: tts.google_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: '''{{ ["Welcome Home good looking", "Welcome home Nicole", "Welcome
        home Nicole you sexy thing"] | random }}''

        '
  alias: Mum Home
  condition: []
  id: '1511309564165'
  trigger:
  - entity_id: group.mum
    from: not_home
    platform: state
    to: home
- id: '1511835243194'
  alias: Morning Lights off
  trigger:
  - at: 08:00:00
    platform: time
  condition: []
  action:
  - data: {}
    service: script.kitbench
  - entity_id: group.sunset_lights
    service: light.turn_off
- action:
  - alias: Bedlight
    data:
      brightness: 50
    service: light.turn_on
    entity_id: light.bedroom_lamps
  alias: Sunset bedroom on
  condition: []
  id: '1512165690720'
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
- action:
  - data:
      message: Ella Bella it's Bedtime.
    service: tts.google_say
  alias: Bedtime Ella
  condition: []
  id: '1513404186571'
  trigger:
  - at: '20:00'
    platform: time
- action:
  - data:
      message: Ready
    service: tts.google_say
  alias: Home restarted
  condition: []
  id: '1513404401372'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      message: Ethan, It's bedtime buddy.
    service: tts.google_say
  alias: Ethan Bedtime
  condition: []
  id: '1514770339871'
  trigger:
  - at: '20:30'
    platform: time
- action:
  - entity_id: switch.bedroom_air
    service: switch.turn_off
  alias: 3am bedroom aircon off
  condition:
  - condition: state
    entity_id: group.parents
    state: home
  id: '1516612143501'
  trigger:
  - at: 03:00:00
    platform: time
- action:
  - data:
      message: it's lunch time..... Nom nom nom
    service: tts.google_say
  alias: Lunch
  condition: []
  id: '1513404186579'
  trigger:
  - at: '12:00'
    platform: time
- action:
    service: tts.google_say
    entity_id: media_player.living_room_speaker
    data_template:
      message: '''{{ ["It''s time for a shower. Ethan", "It''s time for a shower.
        Ella"] | random }}''

        '
  alias: Shower time
  condition: []
  id: '1517455089975'
  trigger:
  - at: '17:00'
    platform: time
- action:
  - data: {}
    service: script.aircon_on
    entity_id: script.aircon_on
  alias: Air Conditioner
  condition: []
  id: '1522283659585'
  trigger:
  - entity_id: input_boolean.air_con
    platform: state
    to: 'on'
- action:
  - service: script.aircon_off
  alias: Air off
  condition: []
  id: '1522284267711'
  trigger:
  - entity_id: input_boolean.air_con
    platform: state
    to: 'off'
- action:
  - service: script.cin_air_on
  alias: Cinema air on
  condition: []
  id: '1522286679217'
  trigger:
  - entity_id: input_boolean.cin_air
    platform: state
    to: 'on'
- action:
  - service: script.cin_off
  alias: Cinema air off
  condition: []
  id: '1522286829021'
  trigger:
  - entity_id: input_boolean.cin_air
    platform: state
    to: 'off'
- id: '1522896103576'
  alias: Dad's Home
  trigger:
  - entity_id: group.dad
    from: not_home
    platform: state
    to: home
  condition: []
  action:
  - delay: 00:00:30
  - data_template:
      message: '''{{ ["Hey Shayne. Welcome home.", "Welcome home Shayno you handsome
        devil", "Welcome home Master"] | random }}''

        '
    entity_id: media_player.living_room_speaker
    service: tts.google_say
  - alias: ''
    data: {}
    entity_id: light.tv_blue
    service: light.turn_on
  - data: {}
    service: light.turn_on
    entity_id: light.gateway_light_7811dcdec559
- id: '1527073470506'
  alias: Frontdoor light on
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.front_door
    service: light.turn_on
- id: '1527073656746'
  alias: frontdoor light off
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    for:
      minutes: 5
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: light.front_door
    service: light.turn_off
- id: '1530705730740'
  alias: House empty shutdown
  trigger:
  - entity_id: group.everyone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - service: light.turn_off
- id: '1530827609534'
  alias: Sunsetlights are on
  trigger:
  - entity_id: group.everyone
    from: not_home
    platform: state
    to: home
  - event: sunset
    platform: sun
  condition:
    condition: and
    conditions:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: group.everyone
      state: home
  action:
  - entity_id: group.sunset_lights
    service: light.turn_on
  - entity_id: script.kitbench
    service: script.turn_on
  - data:
      message: Nighttime lights are now on
    entity_id: media_player.living_room_speaker
    service: tts.google_say
- alias: Spotify Volume (Set)
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state | int / 100  }}'
  id: 0f02de4bd8ba496083742ca8946f28f7
- alias: Spotify Volume (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_volume
  action:
  - delay:
      seconds: 5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.spotify_volume
      value: '{{  states.sensor.spotify_volume.state | float | round(2) * 100  }}'
  id: e5cff8324f6a49848dfcab4e264dc778
- alias: Spotify Shuffle (Set)
  trigger:
    platform: state
    entity_id: input_boolean.spotify_shuffle
  action:
    service: media_player.shuffle_set
    data_template:
      entity_id: media_player.spotify
      shuffle: '{% if is_state(''input_boolean.spotify_shuffle'', ''off'') %}  false
        {% elif is_state(''input_boolean.spotify_shuffle'', ''on'') %} true {% endif
        %}

        '
  id: 2b5e6947613b42089a6c8183c7905618
- alias: Spotify Shuffle (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_shuffle
  action:
  - delay:
      seconds: 5
  - service_template: "{% if states.sensor.spotify_shuffle.state == 'False' %}\n \
      \ input_boolean.turn_off\n{% else %}\n  input_boolean.turn_on\n{% endif %}\n"
    data:
      entity_id: input_boolean.spotify_shuffle
  id: 5d7457c1c99947949e60a03feb0b09fd
- alias: Spotify Source (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_source
  action:
    service: input_select.select_option
    entity_id: input_select.spotify_source
    data_template:
      option: '{{  states.sensor.spotify_source.state  }}'
  id: 5b208dd18b354e43acd55b9e0cb2108e
- id: '1531524034010'
  alias: spotify pause
  trigger:
  - entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - service: media_player.media_pause
    entity_id: media_player.spotify
- id: '1531902807023'
  alias: Ella motion
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000237a778
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '200'
    condition: numeric_state
    entity_id: sensor.illumination_158d000237a778
  action:
  - entity_id: switch.wall_switch_158d0002416083
    service: switch.turn_on
- id: '1510988837827'
  alias: Hall on dark outside
  trigger:
  - below: '700'
    entity_id: sensor.illumination_7811dcdec559
    platform: numeric_state
  condition:
  - after: sunrise
    before: sunset
    condition: sun
  action:
  - alias: hall
    entity_id: light.hallway
    service: light.turn_on
- id: '1531959692321'
  alias: Hall off bright
  trigger:
  - above: '800'
    entity_id: sensor.illumination_7811dcdec559
    platform: numeric_state
  condition: []
  action:
  - entity_id: light.hallway
    service: light.turn_off
- id: '1532412977216'
  alias: Ella motion off
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000237a778
    for:
      minutes: 10
    platform: state
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.wall_switch_158d0002416083
