darkred:
# Main colors that can be changed
  dark-primary-color: "#c66900"
  disabled-text-color: "#545454"
  divider-color: "rgba(255, 255, 255, 0.12)"
  light-primary-color: "#e06c6c"
  paper-card-background-color: "#1d1d1d"
  paper-grey-200: "#191919"
  paper-item-icon-color: "#d3d3d3"
  paper-listbox-background-color: "#202020"
  primary-background-color: "#303030"
  primary-color: "#d32f2f"
  primary-text-color: "#cfcfcf"
  secondary-background-color: "#131313"
  sidebar-text_-_background: "#62717b" 
# Colors based on variables, see above
  paper-card-header-color: "var(--paper-item-icon-color)" 
  paper-item-icon-active-color: "var(--primary-color)"
  paper-item-icon_-_color: "var(--primary-text-color)"
  paper-listbox-color: "var(--primary-text-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"
  paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
  paper-toggle-button-checked-button-color: "var(--primary-color)"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  secondary-text-color: "var(--primary-color)"
  table-row-background-color: "var(--paper-card-background-color)"
  table-row-alternative-background-color: "var(--sidebar-text_-_background)"
  
darkcyan:
# Main colors that can be changed
  primary-color: "#27585e"
  disabled-text-color: "#545454"
  divider-color: "#848383"
  paper-card-background-color: "#8c8888"
  paper-grey-200: "#b7b0b0"
  paper-item-icon-color: "#000000"
  paper-listbox-background-color: "#8e8b8b"
  paper-listbox-color: "#FFFFFF"      
  primary-background-color: "#303030"
  primary-text-color: "#000000"      
  secondary-background-color: "#000000"
  secondary-text-color: "#c4700b"
# Colors based on variables, see above
  label-badge-background-color: "#4e4e4e"
  label-badge-text-color: "#443e3c"
  paper-card-header-color: "#var(--paper-item-icon-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-item-icon-active-color: "#fc4502"
  paper-item-icon_-_color: "#c4700b"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"     
  paper-toggle-button-checked-ink-color: "#004df4"
  paper-toggle-button-checked-button-color: "#ff0000"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  
  
Night_Theme:
  # Main Stuff #
  primary-color: "#0b3e66" # Primary (most of the UI)
  primary-background-color: "#060606" # Primary background colour (dialogs, e.t.c)
  secondary-background-color: "#060606" # Secondary background colour (main UI background)
  paper-card-background-color: "#728f96" # Card background colour
  paper-item-icon-color: "#0843d8" # Icon colour
  primary-text-color: "#000000" # Primary text colour
  secondary-text-color: "#fcfdff" # Secondary text colour
  disabled-text-color: "#3b3c3f" # Disabled text colour
  divider-color: "#3b3c3f" # Divider colour
  paper-card-header-color: "#000000" # Card header text colour
  label-badge-text-color: "#000000" # Main text
  
  # Nav Menu #
  paper-listbox-background-color: "#131313" # Listbox background colour
  paper-listbox-color: "#FFFFFF" # Listbox text colour
  paper-grey-200: "#1c3a63" # Listbox selected item background colour

  # Switches #
  paper-toggle-button-checked-ink-color: "#d80129"
  paper-toggle-button-checked-button-color: "#ff0000"
  paper-toggle-button-checked-bar-color: "#FFFFFF"

  # Sliders #
  paper-slider-knob-color: "#0179d8"
  paper-slider-knob-start-color: "#0179d8"
  paper-slider-pin-color: "#0179d8"
  paper-slider-active-color: "#0179d8"
  paper-slider-secondary-color: "#0179d8"

 
  
